### ISSUE TITLE
FT.DROPINDEX, with args beginning with: Person:index

### ISSUE THREAD

**Issue by supanut1911** [redis-developer/redis-om-node-tutorial#3]
I got the [ErrorReply: ERR unknown command FT.DROPINDEX, with args beginning with: Person:index, ] at terminal

and I try to debug -> try to comment and I think I found error at function createIndex().

I try to down grade the node version and lib redis and redis-om but still not work.

lib dependencies
"redis": "^4.0.4",
"redis-om": "^0.2.0",

mac m1
node v18.18.2
npm 9.8.1

**Comment by supanut1911** [comment]
Okay the issue is about "redis" -> my solution is use 

```
docker run -d --name redis-stack-server -p 6379:6379 redis/redis-stack-server:latest
```

or

```
version: "3.2"
services:
  redis:
    image: "redis/redis-stack-server:latest"
    ports:
      - "6379:6379"

```
